services:
  db:
    image: postgres:16
    container_name: family_bot_db
    restart: always
    environment:
      POSTGRES_DB: family_bot
      POSTGRES_USER: family_bot
      POSTGRES_PASSWORD: family_bot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
